local shell = require('shell')
shell.execute('del main.lua')
shell.execute('del /lib/graphic.lua')
shell.execute('del /lib/colours.lua')
shell.execute('wget https://raw.githubusercontent.com/asdflj/minecraft_opencomputer_program/master/furnace/main.lua')
shell.execute('wget https://raw.githubusercontent.com/asdflj/minecraft_opencomputer_program/master/furnace/lib/color.lua /lib/color.lua')
shell.execute('wget https://raw.githubusercontent.com/asdflj/minecraft_opencomputer_program/master/furnace/lib/graphic.lua /lib/graphic.lua')
